---
version: '3.6'

services:
  server-build-docs:
    container_name: server-build-docs
    image: server-build-docs:latest
    build:
      context: ..
      dockerfile: ./docsify/Dockerfile
    ports:
    - 6007:80
    restart: unless-stopped
